# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-dark.toml

[mode]
normal_alt  = { bg = "blue" }

[indicator]
padding = { open = " ", close = "" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[tabs]
active   = { fg = "black", bg = "lightblue" }
inactive = { fg = "lightblue", bg = "reset" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[icon]
dirs = []
files = []
exts = []
conds = []

[filetype]
rules = [
    { url = "*", is = "link", fg = "lightgreen" },
    { url = "*/", is = "link", fg = "lightgreen" },
    { url = "*", fg = "white" },
    { url = "*/", fg = "lightblue" },
]

[plugin]
preloaders = []
previewers = [
    { url = "*/", run = "folder", sync = true },
    { mime = "text/*", run = "code" },
    { mime = "application/{javascript,json}", run = "code" },
]
